name: release
description: Upload the artifacts to a release
author: php

branding:
  icon: package
  color: purple

inputs:
  release:
    description: 'Git reference for the release'
    required: true
  token:
    description: 'GitHub token'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Get artifacts
      uses: actions/download-artifact@v5
      with:
        path: artifacts
        merge-multiple: true

    - name: Upload artifacts
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: gh release upload ${{ inputs.release }} artifacts/php* --clobber
