name: build-php
description: Build PHP
author: php

branding:
  icon: package
  color: purple

inputs:
  php-version:
    description: PHP version to build
    required: true
  arch:
    description: Architecture to build
    required: true
  ts:
    description: Thread safety to build
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build PHP
      shell: pwsh
      run: |
        Import-Module ${{ github.action_path }}\BuildPhp -Force
        Invoke-PhpBuild -PhpVersion ${{inputs.php-version}} `
                        -Arch ${{inputs.arch}} `
                        -Ts ${{inputs.ts}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v5
      with:
        name: artifacts-${{inputs.php-version}}-${{inputs.arch}}-${{inputs.ts}}
        path: artifacts/*
